#!/usr/bin/env sh

power="BAT0"
battery_discharging="Discharging"
battery_charging="Charging"

get_battery_status() {
  status=$(cat /sys/class/power_supply/$power/status)
  if [[ $status == $battery_charging ]]
  then
    echo "+"
  elif [[ $status == $battery_discharging ]]
  then
    echo "-"
  else
    echo ""
  fi
}

get_battery_capacity() {
  echo -n $(cat /sys/class/power_supply/$power/capacity)
}

printf "%s%d%%" $(get_battery_status) $(get_battery_capacity)
