#!/usr/bin/env sh

get_backlight() {
  echo $(brightnessctl get)
}

get_backlight_max() {
  echo $(brightnessctl max)
}

percent_backlight() {
  echo $((100 * $(get_backlight) / $(get_backlight_max)))
}

get_icon() {
  perc=$(percent_backlight)

  if [[ ($perc -ge 0) && ($perc -le 35) ]]; then
    echo "brightness-low-symbolic"
  elif [[ ($perc -ge 35) && ($perc -le 70) ]]; then
    echo "brightness-medium-symbolic"
  elif [[ ($perc -ge 70) && ($perc -le 100) ]]; then
    echo "brightness-high-symbolic"
  fi
}

notify_cmd() {
  title="Brightness"
  message=$(percent_backlight)%
  progress=$(percent_backlight)%
  icon=$(get_icon)
  id=0x62

  dunstify --urgency normal $title $message --hints int:value:$progress --icon=$icon --replace=$id
}

inc_backlight() {
  brightnessctl set $(($(get_backlight) + 50))
  paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga
}

dec_backlight() {
  brightnessctl set $(($(get_backlight) - 50))
  paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga
}

help() {
  echo "Usage: ./brightness [OPTION]"
  echo -e "--get\t\tGet backlight"
  echo -e "--inc\t\tIncrease backlight +5"
  echo -e "--dec\t\tDecrease backlight +5"
}

if [[ $# -ne 1 ]]; then
  help
  exit 1
fi

if [[ $1 == "--get" ]]; then
  printf "%d%%" $(percent_backlight)
elif [[ $1 == "--inc" ]]; then
  inc_backlight
  notify_cmd
elif [[ $1 == "--dec" ]]; then
  dec_backlight
  notify_cmd
else
  help
  exit 1
fi
