#!/usr/bin/env sh

interface=$(ip route get 1.1.1.1 | awk '{print $5}')

if [[ $interface == "" ]]
then
  exit
fi

tx_bytes_last=$(cat /sys/class/net/$interface/statistics/tx_bytes)
rx_bytes_last=$(cat /sys/class/net/$interface/statistics/rx_bytes)

sleep 1

tx_bytes_now=$(cat /sys/class/net/$interface/statistics/tx_bytes)
rx_bytes_now=$(cat /sys/class/net/$interface/statistics/rx_bytes)

tx_bytes=$(($tx_bytes_now - $tx_bytes_last))
rx_bytes=$(($rx_bytes_now - $rx_bytes_last))

tx_mbps=$(echo "$tx_bytes*0.000008" | bc)
rx_mbps=$(echo "$rx_bytes*0.000008" | bc)

printf " %.2f  %.2f Mbps" $tx_mbps $rx_mbps
