#!/usr/bin/env sh

INTERFACE=$(ip addr | awk '/state UP/ {print $2}' | sed 's/.$//')

if [[ "$INTERFACE" == "" ]]
then
  exit
fi

TX_BYTES_1=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)
RX_BYTES_1=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)

sleep 1

TX_BYTES_2=$(cat /sys/class/net/$INTERFACE/statistics/tx_bytes)
RX_BYTES_2=$(cat /sys/class/net/$INTERFACE/statistics/rx_bytes)

TX_BYTES=$(($TX_BYTES_2 - $TX_BYTES_1))
RX_BYTES=$(($RX_BYTES_2 - RX_BYTES_1))

TX_MBPS=$(echo "$TX_BYTES*0.000008" | bc)
RX_MBPS=$(echo "$RX_BYTES*0.000008" | bc)

printf " %.2f Mbps  %.2f Mbps" $TX_MBPS $RX_MBPS
