#!/usr/bin/env sh

info=$(cat /proc/meminfo)

total=$(echo $info | awk '{print $2}')
free=$(echo $info | awk '{print $5}')
buffers=$(echo $info | awk '{print $11}')
cached=$(echo $info | awk '{print $14}')

usage=$((100 * (($total - $free) - ($buffers + $cached)) / $total))

printf "%d%%" $usage
